image: debian:11

definitions:
  steps:
    - step: &build-on-debian
        name: Build and Publish on Debian
        image: debian:11
        script:
          - ls -lah
          - sh 01-resolve-debian-dependencies.sh
          - sh 02-compile-guacamole.sh
          - sh 03-create-deb.sh
          - ls -lah /
          - sh 04-publish.sh
            
    - step: &build-on-ubuntu
        name: Build and Publish on Ubuntu
        image: ubuntu:20.04
        script:
          - sh 01-resolve-debian-dependencies.sh
          - sh 02-compile-guacamole.sh
          - sh 03-create-deb.sh
          - ls -lah
          - sh 04-publish.sh

pipelines:
  tags:
    # git tag debian-$(date +%Y-%m-%d-%H%M%S) -m "Debian build $(date +%c)" && git push --follow-tags
    # to trigger building the Debian package
    debian-*:
      - step: *build-on-debian
    # git tag ubuntu-$(date +%Y-%m-%d-%H%M%S) -m "Ubuntu build $(date +%c)" && git push --follow-tags
    # to trigger building the Ubuntu package
    ubuntu-*:
      - step: *build-on-ubuntu