image: debian:11

definitions:
  steps:
    - step: &build-on-debian
        name: Build and Publish on Debian
        image: debian:11
        script:
          - ls -lah
          - sh 01-resolve-debian-dependencies.sh
          - sh 02-compile-guacamole.sh
          - sh 03-create-deb.sh
          - ls -lah /
          - sh 04-publish.sh rport-guacamole_1.4.0_debian_bullseye_amd64.deb
            
    - step: &build-on-ubuntu
        name: Build and Publish on Ubuntu
        image: ubuntu:20.04
        script:
          - sh 01-resolve-debian-dependencies.sh
          - sh 02-compile-guacamole.sh
          - sh 03-create-deb.sh
          - ls -lah
          - sh 04-publish.sh rport-guacamole_1.4.0_ubuntu_focal_amd64.deb

pipelines:
  branches:
    main:
      - step: *build-on-debian